apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  labels:
    app: proxy
spec:
  replicas: 5
  selector:
    matchLabels:
      app: proxy
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 2
  template:
    metadata:
      labels:
        app: proxy
    spec:
      containers:
      - name: nginx
        image: nginx:1.9
       
