apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2020-12-15T07:39:39Z"
  labels:
    app: nginx
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:labels:
          .: {}
          f:app: {}
      f:spec:
        f:externalTrafficPolicy: {}
        f:ports:
          .: {}
          k:{"port":80,"protocol":"TCP"}:
            .: {}
            f:name: {}
            f:port: {}
            f:protocol: {}
            f:targetPort: {}
        f:selector:
          .: {}
          f:app: {}
        f:sessionAffinity: {}
        f:type: {}
    manager: kubectl-create
    operation: Update
    time: "2020-12-15T07:39:39Z"
  name: nginx
  namespace: default
  resourceVersion: "76757"
  selfLink: /api/v1/namespaces/default/services/nginx
  uid: 91d8dbfa-b7f1-4339-95b7-8d84dae8443e
spec:
  clusterIP: 10.101.246.24
  externalTrafficPolicy: Cluster
  ports:
  - name: 80-80
    nodePort: 32634
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: nginx
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}
