apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2020-12-15T07:28:24Z"
  labels:
    app: proxy
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:labels:
          .: {}
          f:app: {}
      f:spec:
        f:externalTrafficPolicy: {}
        f:ports:
          .: {}
          k:{"port":80,"protocol":"TCP"}:
            .: {}
            f:port: {}
            f:protocol: {}
            f:targetPort: {}
        f:selector:
          .: {}
          f:app: {}
        f:sessionAffinity: {}
        f:type: {}
    manager: kubectl-expose
    operation: Update
    time: "2020-12-15T07:28:24Z"
  name: nginx
  namespace: default
  resourceVersion: "76261"
  selfLink: /api/v1/namespaces/default/services/nginx
  uid: a72525a7-6b15-424f-867f-699675c19b0d
spec:
  clusterIP: 10.107.78.1
  externalTrafficPolicy: Cluster
  ports:
  - nodePort: 30139
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: proxy
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}
