apiVersion: apps/v1
kind: Deployment
metadata:
  name: httpd
  labels:
    app: httpd
spec:
  replicas: 5
  selector:
    matchLabels:
      app: httpd
  template:
    metadata:
      labels:
        app: httpd
    spec:
      volumes:
        - name: nfs-pv
          persistentVolumeClaim:
            claimName: pv-claim
      containers:
      - name: httpd
        image: httpd
        volumeMounts:
          - mountPath: "/usr/local/apache2/htdocs"
            name: nfs-pv
