apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
  name: echoserver
spec:
  rules:
  - host:  ingress.httpd.com
    http:
      paths:
      - backend:
          serviceName: httpd
          servicePort: 80
        path: /
  - host: ingress.nginx.com
    http:
      paths:
        - path: /*
          backend:
            serviceName: nginx
            servicePort: 80
